name: EnvironmentVariable Project
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Run tests
        run: |
            echo '${{ secrets.DBPASSWORD }}'
            echo $DBPASSWORD